language: node_js
node_js:
  - "10.16.3"
  - "12.14.1"
after_success: npm run report && npm run coveralls
before_deploy:
  # Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
  - |
    function npm_dist_tag() {
      if [[ "$TRAVIS_TAG" = *"-"* ]]; then
        echo "next"
      else
        echo "latest"
      fi
    }
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    tag: $(npm_dist_tag)
    on:
      tags: true
      repo: ariari-co/ariari-accounts-sdk
      node: 12.14.1
